const errCodes = {
  "0": "成功",
  "-100": "已登出"

  // UNKONW_ERROR(-1, "系统异常,请刷新后重试"),
  //   FLOW_NOT_EXIST_ERROR(-2, "不存在此流程"),
  //   SERVER_NOT_EXIST_ERROR(-3, "不存在此服务器"),
  //   SAVE_TASK_FAIL(-4, "任务保存失败"),
  //   TASK_NOT_EXIST_ERROR(-5, "不存在此任务"),
  //   ARGS_ERROR(-6, "参数错误"),
  //   LOAD_TREE_FAIL(-7, "加载目录失败"),
  //   GET_FILE_FAIL(-8, "获取文件失败"),
  //   UPLOAD_FAIL(-9, "上传文件失败"),
  //   GET_SYSINFO_FAIL(-10, "获取服务器信息失败"),
  //   EXEC_TASK_FAIL(-11, "启动任务失败"),
  //   GET_ERROR_LOG_FAIL(-12, "获取错误日志失败"),
  //   TASK_NAME_REPET(-13, "任务名称重复"),
  //   UPDATE_TASK_FAIL(-14, "修改任务失败"),
  //   NOT_SYS_USER(-15, "非正式用户"),
  //   NOT_OUTPUT_PATH(-16, "未配置任务输出路径"),
  //   CREATE_USER_FAIL(-17, "创建用户失败"),
  //   USERNAME_EXIST(-18, "用户名已存在"),
  //   EMAIL_EXIST(-19, "邮箱已存在"),
  //   USER_NOT_EXIST(-20, "用户不存在"),
  //   EMAIL_ERROR(-21, "邮箱错误"),
  //   SEND_EMAIL_FAIL(-22, "发送邮件失败"),
  //   SEND_EMAIL_FAIL_CAUSE_CACHE_INVALID(-23, "缓存失效导致发送邮件失败"),
  //   MODULE_DEPENDENCY_LIST_NULL(-24, "创建模块依赖列表为空"),
  //   NO_PASSWORD(-25, "登录时未获取密码"),
  //   LINUX_AUTH_FAIL(-26, "服务器账号密码错误"),
  //   HAS_TOO_MANAY_SERVER(-27, "一个域下包含多台服务器"),
  //   HAS_NO_CUSTOM_FIELD(-28, "没有对应自定义信息"),
  //   PHONE_EXIST(-29, "手机已存在"),
  //   PASSWORD_NOT_MATCHING(-30, "旧密码错误"),
  //   USER_RECORD_NOT_FOUND(-31, "未找到对应用户行为记录"),
  //   DOMAIN_NOT_FOUND(-32, "未注册的域"),
  //   HAS_TOO_MANY_PUBLIC_ACCOUNT(-33, "一个域下包含多个公共服务器账号"),
  //   NOT_BINDING_SERVER(-34, "未绑定服务器账号"),
  //   NOT_BINDING_PUBLIC_ACCOUNT(-35, "未绑定公共账号"),
  //   CREATE_PRIVATE_DIR_FAIL(-36, "创建用户私有文件夹失败"),
  //   DEL_TASK_FAIL(-37, "删除失败"),
  //   DOMAIN_HAS_NO_SERVER(-38, "域下未注册服务器"),
  //   HAS_TOO_MANY_SERVER_INFO(-39, "同域下存在多个相同服务器账号"),
  //   USER_TYPE_ERROR(-40, "用户类型错误"),
  //   DOWNLOAD_FAIL(-41, "下载失败"),
  //   FAILED_TO_GET_DATA(-42, "获取数据失败"),
  //   APPROVED(-43, "已审批"),
  //   CHANNEL_EXEC_TIMEOUT(-44, "服务器执行命令超时"),
  //   SERVER_AUTH_FAILED(-45, "服务器认证失败"),
  //   GET_SERVER_SESSION_FAILED(-46, "获取服务器会话失败"),
  //   GET_PERMISSION_FAILED(-47, "获取权限失败"),
  //   SPECIES_NAME_VERSION_EXIST(-48, "物种名称与版本已存在"),
  //   CSV_FORMART_ERROR(-49, "上传文件格式错误"),
  //   NO_ACCESS_ERROR(-50, "没有权限，请联系管理员！"),
  //   SERVER_BUSY(-51, "服务器繁忙，请稍候再试！"),
  //   TASK_SCRIPT_ERROR(-52, "执行任务的python脚本不存在"),
  //   SERVER_USER_NO_ACCESS_ERROR(-53, "指定目录下创建目录失败,可能是该用户没有在指定目录下创建目录的权限,请联系管理员！"),
  //   CSV_ILLEGAL_CHAR(-55, "匹配失败，文件中含有非法字符，请修改后重新上传！"),
  //   SERVER_EXCEPTION(-56, "服务器异常,请稍后重试！"),
  //   CHECK_SERVER_EXCEPTION(-57, "检测到服务器连接异常，无法实时获取文件信息，可使用已展示文件创建任务。若需获取新增文件信息，请稍后再试。"),
  //   L_CHECK_PERSONAL_ACCOUNT(-58, "检测到本账号绑定的服务器密码发生变动，无法连接获取服务器信息，仅能使用已展示文件创建并保存任务。若需获取新增文件信息或运行任务请前往个人中心修改服务器密码后再进行操作。"),
  //   L_CHECK_COMMON_ACCOUNT(-59, "检测本账号绑定的服务器密码发生变动，无法连接获取服务器信息，仅能使用已展示文件创建并保存任务。已通知管理员进行服务器密码修改操作，密码修改成功后将以邮件形式通知您。"),
  //   E_CHECK_PERSONAL_ACCOUNT(-58, "检测到本账号绑定的服务器密码发生变动，无法连接到服务器启动任务，请保存任务后前往个人中心修改服务器密码。"),
  //   E_CHECK_COMMON_ACCOUNT(-59, "检测本账号绑定的服务器密码发生变动，无法连接到服务器启动任务，已通知管理员进行服务器密码修改操作，密码修改成功后将以邮件形式通知您，请先保存任务并等候通知。"),
  //   DELETE_INTERMEDIATE_FILE_FAILUE(-60, "删除任务的中间文件失败"),
  //   PASSWORD_FAILD(-61, "密码错误，无法连接到服务器，请重新输入"),
  //   TASK_ROOFPLACEMENT_FAILD(-62, "任务置顶失败,请稍后重试"),
  //   TASK_ISNOT_RUN(-63, "任务处于非运行状态"),
  //   NO_RUNNING_PERMISSION(-64, "该账号目前没有开通任务运行权限，若需要继续运行任务，请与管理员联系"),
  //   TASK_HAS_BEEN_PLACED_AT_THE_TOP(-65, "任务已置顶"),
  //   ONLY_ONE_MANAGER(-66, "管理员账号已经存在"),
  //   COMMON_NOT_EXIST(-67, "公用账号不存在"),
  //   USERNAME_EMAIL_CAN_NOT_BE_EMPTY(-68, "用户名或邮箱不能为空"),
  //   DOMAIN_NAME_IS_EXIST(-69, "域名已存在"),
  //   URL_CAN_NOT_BE_EMPTY(-70, "主页地址不能为空"),
  //   TASK_SAVE_SUCESS(0, "任务已保存"),
  //   TASK_SAVE_RUN(0, "任务已保存并运行"),
  //   TASK_Name_IS_EXIST(-71, "任务名称已存在"),
  //   DOMAIN_NAME_IS_NOT_EXIST(-72, "域名不存在或已禁用"),
  //   INIT_FAILD(-73,"初始化服务器根目录失败"),
  //   FAILURE_OF_ASSOCIATED_PUBLIC_ACCOUNT(-74,"管理员关联公共服务器账号失败"),
  //   EXISTING_ACCOUNTS_IN_THE_DOMAIN(-75,"当前域下已有公共账号"),
  //   FLOW_DOES_NOT_EXIST(-76,"所选流程不存在，请重新编辑任务信息"),

  //   AUTH_ERROR(-100, "认证失败"),
  //   ACCESS_ERROR(-101, "授权失败"),
  //   REMOTE_LOGIN(-102, "异地登录"),
  /*   ALREADY_CLEAR_CACHE(-103,"已清token,请重新登录！"),
    ALREADY_LOGOUT(-104, "已登出"),*/
};
